-- MySQL Script generated by MySQL Workbench
-- Fri Feb  8 10:33:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Kursanci
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Kursanci
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Kursanci` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `Kursanci` ;

-- -----------------------------------------------------
-- Table `Kursanci`.`Kurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kursanci`.`Kurs` (
  `idKurs` INT NOT NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idKurs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kursanci`.`Uczestnicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kursanci`.`Uczestnicy` (
  `idUczestnicy` INT NOT NULL AUTO_INCREMENT,
  `Imię` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Kurs_idKurs` INT NOT NULL,
  PRIMARY KEY (`idUczestnicy`),
  INDEX `fk_Uczestnicy_Kurs_idx` (`Kurs_idKurs` ASC) VISIBLE,
  CONSTRAINT `fk_Uczestnicy_Kurs`
    FOREIGN KEY (`Kurs_idKurs`)
    REFERENCES `Kursanci`.`Kurs` (`idKurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
